# Generated by Django 3.1.1 on 2022-09-08 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_auto_20220908_0648'),
    ]

    operations = [
        migrations.RenameField(
            model_name='category',
            old_name='parent_id',
            new_name='parent_category',
        ),
    ]
